title = "Website Name"
baseURL = 'https://example.org'
disableHugoGeneratorInject = true
uglyURLs = true
theme = 'cleogo'

[params]
  copyright = 'Made with Cleogo'
  cphref = "https://github.com/Cleomancy/cleogo/" # copyright href
  favicon = "/favicon.ico"
  logo = "/logo.png"
  description = 'lol'
  smdesc = 'sitemap'

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[markup]
  defaultMarkdownHandler = 'goldmark'

    [markup.goldmark.parser.attribute]
      block = false
      title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = true
    [markup.goldmark.extensions.typographer]
      apostrophe = '&#39;'
      disable = false
      ellipsis = '&#8230;'
      emDash = '&#8212;'
      enDash = '&#8211;'
      leftAngleQuote = '&#8249;'
      leftDoubleQuote = '&#8220;'
      leftSingleQuote = '&#8216;'
      rightAngleQuote = '&#8250;'
      rightDoubleQuote = '&#8221;'
      rightSingleQuote = '&#8217;'
    [markup.highlight]
      anchorLineNos = false
      codeFences = false
      guessSyntax = false
      hl_Lines = ''
      hl_inline = false
      lineAnchors = ''
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = true
      noClasses = true
      noHl = true
      style = 'monokai'
      tabWidth = 4

[outputFormats]
  [outputFormats.xhtml]
    baseName = 'index'
    isHTML = true
    mediaType = 'application/xhtml+xml'

[mediaTypes]
  [mediaTypes.'application/xhtml+xml']
    suffixes = ['xhtml']

[outputs]
  home = ['xhtml', 'rss']
  page = ['xhtml']
  rss = ['rss']
  section = ['xhtml']
  taxonomy = ['xhtml']
  term = ['xhtml']

[menu]
[[menu.main]]
  name = 'Home'
  url = '/index.xhtml'
  weight = 10
[[menu.main]]
  name = 'Tags'
  url = '/tags.xhtml'
  weight = 20
[[menu.footer]]
  name = 'Home'
  url = '/index.xhtml'
  weight = 10
[[menu.footer]]
  name = 'Sitemap'
  url = '/sm.xhtml'
  weight = 20

[languages]
  [languages.en]
    languageName = 'English'
    #title = 'In English'
    contentDir = "content/english"
    weight = 1
  [languages.fr]
    languageName = 'Français'
    #title = 'En Français'
    contentDir = "content/french"
    weight = 2
  [languages.fr.params]
    description = 'lolfr'
    favicon = "/favicon.ico"
    logo = "/logo.png"
    smdesc = 'sitemapfr'
    copyright = 'Propulsé par cleogo'
    cphref = "https://github.com/Cleomancy/cleogo/" # copyright href
  [languages.fr.menu]
      [[languages.fr.menu.main]]
        name = 'Accueil'
        pageRef = '/'
        weight = 10
      [[languages.fr.menu.main]]
        name = 'Tags'
        pageRef = 'tags.xhtml'
        weight = 20
      [[languages.fr.menu.footer]]
        name = 'Accueil'
        pageRef = '/'
        weight = 10
      [[languages.fr.menu.footer]]
        name = 'Sitemap'
        url = '/fr/sm.xhtml'
        weight = 20
      